version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "net-counter1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g0xfk6t00fde"
s3_prefix = "net-counter1"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VPCId=\"vpc-08fd36d18b9ae9cab\" CWNamespace=\"CUSTOM/VPC_Network_Resource_Tracker\" Schedule=\"5\""
